### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by pfsmorigo** [leoxiong/ingress-intel-timelapse#2]
Both in Fedora and Debian, using phantonjs 2.1.1:

$ phantomjs screenshot.js 
opening https://www.ingress.com/intel?ll=-37.775176,175.264924&z=12
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Segmentation fault (core dumped)

I just change CSRF and SACSID lines in screenshot.js and hit this segfault.

I can help debugging it. What's the best way to do it?

**Comment by leoxiong** [comment]
If PhantomJS still crashes, please let me know :).
