### ISSUE TITLE
Working?

### ISSUE THREAD

**Issue by reiven** [leoxiong/ingress-intel-timelapse#3]
Is this still working?

**Comment by neon-ninja** [comment]
Hi - this PR should get it working again https://github.com/leoxiong/ingress-intel-timelapse/pull/4

**Comment by leoxiong** [comment]
Sorry, I have been away. Thanks @neon-ninja, I'll get that merged.

**Comment by reiven** [comment]
I still cannot make it work , neither on linux or osx :(

On OSX i'm getting
```
opened
TypeError: null is not an object (evaluating 'document.getElementById('level_low' + portal_min_level).dispatchEvent')

  undefined:4
  :22
loading intel...
TypeError: null is not an object (evaluating 'document.getElementById('loading_msg').style')

  undefined:2
  :3
TypeError: null is not an object (evaluating 'document.getElementById('percent_text').innerHTML')
```

**Comment by neon-ninja** [comment]
Hi @reiven  - what version of phantomjs are you using? I have 2.1.1.
Can you try run phantomjs with the --debug=true flag?

**Comment by reiven** [comment]
hi @neon-ninja , my fault, looks like the csrf token was incomplete and now it is working! 
@leoxiong can you please merge the PR? Thanks!

**Comment by neon-ninja** [comment]
> hi @neon-ninja , my fault, looks like the csrf token was incomplete and now it is working!
> @leoxiong can you please merge the PR? Thanks!

He already has :)

**Comment by reiven** [comment]
Great, thaks @neon-ninja and @leoxiong
